version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8010"
    volumes:
      - .:/app
    ports:
      - "8010:8010"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=edutrack.settings.development

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=edutrack

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: