```
name: EduTrack CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: edutrack_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create logs directory
      run: mkdir -p logs
      
    - name: Run migrations
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/edutrack_test
        DJANGO_SETTINGS_MODULE: edutrack.settings.test
        SECRET_KEY: github_actions_secret_key
        DEBUG: 'True'
      run: python manage.py migrate
        
    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/edutrack_test
        DJANGO_SETTINGS_MODULE: edutrack.settings.test
        SECRET_KEY: github_actions_secret_key
        DEBUG: 'True'
      run: |
        coverage run --source='.' manage.py test
        coverage report
        
    - name: Run lint checks
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
```